wahoo: Squash Import gpt-utils
This is a squash of the following:

Author: Akilesh Kailash <akailash@google.com>
Date:   Wed Dec 30 00:49:12 2020 +0000

        fsync after block device writes

        When markBoolSuccessful is invoked, we update
        the partition table. These writes should be
        synced before merge operation is resumed post OTA.
        If not, any crash before these writes are landed to
        backing storage will lead to incorrect switching of
        slots.

        BUG: 175711601
        Test: Verify slot switching correctly after crash when merge in progress
        (on redbull)
        Signed-off-by: Akilesh Kailash <akailash@google.com>
        Change-Id: I4d30342b44aaeb7a4fdc915cc1e53ffb20c17a2f

Author: Rashed Abdel-Tawab <rashed@linux.com>
Date:   Sun Sep 29 15:37:38 2019 -0400

    wahoo: Switch to generated_kernel_headers

    This is a squash of the following:

    Author: razorloves <razorloves@gmail.com>
    Date:   Tue Feb 18 13:38:24 2020 +1100

        wahoo: liblight: use generated kernel headers

        Change-Id: Ib12bf0b7019f9fc1cd6b119e7377fe89d9eaf8f1

    Author: LuK1337 <priv.luk@gmail.com>
    Date:   Sun Sep 27 16:12:10 2020 +0200

        wahoo: gpt-utils: Drop unnecessary include

        * When using generated_kernel_headers including
          stdio.h will cause errors due to redefined macros.

        Change-Id: I2f753a64f760b636be1325873e17697466fbf33d

    Author: LuK1337 <priv.luk@gmail.com>
    Date:   Mon Sep 9 22:38:02 2019 +0200

        wahoo: gpt-utils: Drop unnecessary include

        * When using generated_kernel_headers including
          asm/byteorder.h will cause a warning due to
          unused static functions.

        Change-Id: I2a74ec92487c13c4645048c96da8cb92b3cbd9f0

    Author: Rashed Abdel-Tawab <rashed@linux.com>
    Date:   Sun Sep 29 15:37:38 2019 -0400

        wahoo: Switch gpt-utils to generated_kernel_headers

        Change-Id: Ia6e2f7e140e6ffbd3a93dd823f836aaf399d03fb

    Change-Id: Ia1f608778b5b37fec770abbf185c5e313cd5ba16

Author: Tao Bao <tbao@google.com>
Date:   Wed May 15 10:00:29 2019 -0700

    Deprecate PRODUCT_STATIC_BOOT_CONTROL_HAL.

    In favor of using boot control HAL under recovery.

    Bug: 34254109
    Test: TreeHugger

    This is a combination of 2 commits.
    This is the 1st commit message:

    Revert^2 "Build libgptutils with Android.bp.""

    This reverts commit 215189f0b9ff44d28c2b4ace0abb26854b201271.

    The previous landing broke checkbuild targets due to namespace issue. As
    libgptutils.msm8998 was exposed to global namespace (previously guarded
    via conditionals in Android.mk), but had a missing dependency on
    nonexposed msm8998 kernel headers.

    The relanding adds a Soong namespace of hardware/qcom/msm8998, to ensure
    modules only getting built as needed.

    Bug: 34254109
    Test: Sideload on taimen.
    Test: `m -j checkbuild` with aosp_x86-eng
    Change-Id: I4a7c4cedcf58c7735172d989912e4f7afad1eaed
    Merged-In: I4a7c4cedcf58c7735172d989912e4f7afad1eaed
    (cherry picked from commit e74c7611d2cbea03ec8ec1559787a7a57b2bf767)

    This is the commit message #2:

    Revert^2 "Deprecate PRODUCT_STATIC_BOOT_CONTROL_HAL.""

    This reverts commit d83c2cc22b3f037e94cd4ad7e19f5985da13a8b8.

    The previous landing broke checkbuild targets due to namespace issue.
    See the commit message for hardware/qcom/msm8998 change.

    Bug: 34254109
    Test: Build and boot taimen on device to home screen.
    Test: Sideload on taimen.
    Change-Id: I775026345eb5fc0ec580ba4ca0282835106a1d35
    Merged-In: I775026345eb5fc0ec580ba4ca0282835106a1d35
    (cherry picked from commit 4fa8e490208bef42faccf204381dc35ad1cfed46)

Author: Tao Bao <tbao@google.com>
Date:   Fri Jun 8 13:29:47 2018 -0700

    gpt-utils: Drop -Wno-unused-variable and address one warning.

    hardware/qcom/msm8998/gpt-utils/gpt-utils.cpp:750:17: error: unused variable 'ufs_dir_stat' [-Werror,-Wunused-variable]
        struct stat ufs_dir_stat;
                    ^
    hardware/qcom/msm8998/gpt-utils/gpt-utils.cpp:973:13: error: unused variable 'r' [-Werror,-Wunused-variable]
            int r, fd;
                ^
    hardware/qcom/msm8998/gpt-utils/gpt-utils.cpp:973:16: error: unused variable 'fd' [-Werror,-Wunused-variable]
            int r, fd;
                   ^
    3 errors generated.

    [ 22% 4/18] target  C++: libgptutils <= hardware/qcom/msm8998/gpt-utils/gpt-utils.cpp
    In file included from hardware/qcom/msm8998/gpt-utils/gpt-utils.cpp:54:
    system/core/libcutils/include_vndk/cutils/log.h:38:2: warning: "Deprecated: don't include cutils/log.h, use either android/log.h or log/log.h" [-W#warnings]
     ^
    1 warning generated.

    Test: lunch aosp_walleye-userdebug && m -j libgptutils
    Change-Id: Ie3c33cc61fc62ac93ab0954a9e292b62cfcf9e03

Author: Chih-Hung Hsieh <chh@google.com>
Date:   Tue Nov 7 12:26:51 2017 -0800

    Use -Werror in hardware/qcom/msm8998/gpt-utils

    * Suppress existing warnings.

    Bug: 66996870
    Test: build with WITH_TIDY=1
    Change-Id: If2d100b57d6f29a91ed744263aae75714c8b1bff

Author: Patrick Tjin <pattjin@google.com>
Date:   Tue Jul 25 19:26:13 2017 -0700

    Add aes as A/B OTA partition

    Bug: 37554629
    Change-Id: I162150922683000dbfc0beceab807d46bd51325e

Author: Logan Chien <loganchien@google.com>
Date:   Wed May 17 15:36:58 2017 +0800

    libgptutils: Replace libsparse.so with libz.so

    This commit replaces sparse_crc32() with crc32() from libz.so because
    libsparse.so won't be vendor available.

    Bug: 38303202
    Test: android builds
    Change-Id: Ib318da74b5d55f729cbd40d9a62da53e6316fe7b

Author: Patrick Tjin <pattjin@google.com>
Date:   Wed May 10 15:36:34 2017 -0700

    Add laf partition to swap list.

    Bug: 37743272
    Change-Id: If9521bbd29af9439aa01ac72c8bb8cbc0bf674b6

Author: Isaac Chen <ycchen@google.com>
Date:   Tue May 9 15:44:19 2017 +0800

    Move gptutils lib to vendor for build split

    libgptutils is only used by vendor. Move it to
    vendor partition so they can work with generic AOSP
    system image.

    Bug: 37927875
    Test: These libs are under /vendor/lib(64) instead of
    /system/lib(64) and the resulted image works on the device.
    Change-Id: Id04f7a09fdc8e60de79f83b8fd0c2504fd2e2ebe

    Change-Id: I7f3f8fe845d35a05492ffc4785787622c7851b79

Author: Thierry Strudel <tstrudel@google.com>
Date:   Thu May 4 18:15:01 2017 -0700

    gpt-utils: PTN_SWAP_LIST add the missing new partitions

    abl, dtbo, vbmeta were not part of the list updated by bootctl HAL.
    This will fix the issue but bootctl HAL should be rewritten to not
    detect A/B partition candidate at runtime.

    Bug: 37501587
    Change-Id: I64140d9fce8d142e16a12c9778f1b10394f9dc76
    Signed-off-by: Thierry Strudel <tstrudel@google.com>

Author: Thierry Strudel <tstrudel@google.com>
Date:   Thu Feb 23 15:34:36 2017 -0800

    adding gpt-utils

    Change-Id: Ib39a2dd8319c1b9e5fbbb1fc782237d061046094
    Signed-off-by: Thierry Strudel <tstrudel@google.com>